spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smileroomtidal
    password: adbfedxdqukwutey
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update #how to schema todo before run
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

---
app:
  token:
    secret: m#MySecretGGWP2021
    issuer: BackendService
  email:
    from: smileroomtidal@gmail.com